// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbMvamoiRuHFWuz7xjDI9yi6y5w4eKhg0',
    appId: '1:84659516671:web:c59c8343501c01830fc8ca',
    messagingSenderId: '84659516671',
    projectId: 'sih-app-1372',
    authDomain: 'sih-app-1372.firebaseapp.com',
    storageBucket: 'sih-app-1372.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKpQ45ywZz5giyep42YFxRqeLg-NNGPTk',
    appId: '1:84659516671:android:0640dc189a9b32b30fc8ca',
    messagingSenderId: '84659516671',
    projectId: 'sih-app-1372',
    storageBucket: 'sih-app-1372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOC4IzUkOGwLJiJeO8O_DNoamexlFjsU0',
    appId: '1:84659516671:ios:19b7b5ff59ed205d0fc8ca',
    messagingSenderId: '84659516671',
    projectId: 'sih-app-1372',
    storageBucket: 'sih-app-1372.appspot.com',
    iosBundleId: 'com.lakshya.sihApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOC4IzUkOGwLJiJeO8O_DNoamexlFjsU0',
    appId: '1:84659516671:ios:c01a622766d187d70fc8ca',
    messagingSenderId: '84659516671',
    projectId: 'sih-app-1372',
    storageBucket: 'sih-app-1372.appspot.com',
    iosBundleId: 'com.lakshya.sihApp.RunnerTests',
  );
}
